---
# https://github.com/wpacket/pan-ansible/blob/master/pan_config_pull.yml
- name: Backup Data from Google Keep
  hosts: localhost
  gather_facts: no
  vars:
    # SFTP Server
    sftp_host: "{{ lookup('ansible.builtin.env', 'SFTP_HOST') }}"
    sftp_port: "{{ lookup('ansible.builtin.env', 'SFTP_PORT', default=22) }}"
    sftp_username: "{{ lookup('ansible.builtin.env', 'SFTP_USERNAME') }}"
    sftp_password: "{{ lookup('ansible.builtin.env', 'SFTP_PASSWORD') }}"
    sftp_path: "{{ lookup('ansible.builtin.env', 'SFTP_PATH') }}"
    # Pushover
    pushover_token: "{{ lookup('ansible.builtin.env', 'PUSHOVER_TOKEN') }}"
    pushover_user: "{{ lookup('ansible.builtin.env', 'PUSHOVER_USER') }}"
  tasks:
    - name: Perform Backup
      block:
        - name: Create Backup File Path
          ansible.builtin.set_fact:
            backup_data_file: "GoogleKeep__data__{{ now().strftime('%Y.%m.%d') }}.json"

        - name: Create .downloads/ Directory
          delegate_to: localhost
          ansible.builtin.file:
            path: .downloads/
            state: directory
            mode: '0755'

        - name: Run Extract Script
          delegate_to: localhost
          command: ".venv/bin/python extract.py {{ backup_data_file }}"
        
        - name: Upload Config to SFTP
          delegate_to: localhost
          ansible.builtin.shell: "echo 'put .downloads/{{ backup_data_file }}' | sshpass -p '{{ sftp_password }}' sftp -o StrictHostKeyChecking=no -P {{ sftp_port }} {{ sftp_username }}@{{ sftp_host }}:{{ sftp_path }}"

        - name: Delete Config File Locally
          delegate_to: localhost
          ansible.builtin.file:
            path: ".downloads/{{ backup_data_file }}"
            state: absent

      rescue:
        - name: Notify Admin of Failed Backup
          delegate_to: localhost
          ansible.builtin.uri:
            url: https://api.pushover.net/1/messages.json
            method: POST
            headers: 
              Content-Type: application/json
            body_format: json
            body:
              user: "{{ pushover_user }}"
              token: "{{ pushover_token }}"
              message: "❌ Unable to perform data backup for Google Keep!"
